version: "3"

services:
  grafana:
    restart: always
    container_name: grafana
    image: grafana/grafana
    ports:
      - 3000:3000
    user: "0"
    environment:
          MY_HOST: 192.168.1.240
          GF_LOG_LEVEL: debug
          GF_LOG_CONSOLE_LEVEL: debug   
          GF_SERVER_PROTOCOL: http
          GF_SERVER_DOMAIN: 192.168.1.240
          GF_SERVER_ROOT_URL: http://192.168.1.240:3000
          GF_DASHBOARD_MIN_REFRESH_INTERVAL: 1s
          GF_AUTH_BASIC_ENABLED: 'false'
          GF_AUTH_DISABLE_LOGIN_FORM: 'true'
          GF_AUTH_SIGN_OUT_URL : http://192.168.1.240:3000/auth/realms/412/protocol/openid-connect/logout?redirect_uri=http://192.168.1.240:3000/login
          GF_AUTH_OAUTH_AUTO_LOGIN: 'false'
          GF_AUTH_GENERIC_OAUTH_ALLOWED_DOMAINS: ''
          GF_AUTH_GENERIC_OAUTH_ENABLED: 'true'
          GF_AUTH_GENERIC_OAUTH_TLS_SKIP_VERIFY_INSECURE: 'true'
          GF_AUTH_GENERIC_OAUTH_NAME: Keycloak
          GF_AUTH_GENERIC_OAUTH_ALLOW_SIGN_UP: 'true'
          GF_AUTH_GENERIC_OAUTH_CLIENT_ID: grafana
          GF_AUTH_GENERIC_OAUTH_SCOPES: openid
          GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: fd04a337-8656-4ae3-ab7f-7aa892e47cf2
          GF_AUTH_GENERIC_OAUTH_AUTH_URL: https://collaborauth.dvclab.com/auth/realms/412/protocol/openid-connect/auth
          GF_AUTH_GENERIC_OAUTH_TOKEN_URL: https://collaborauth.dvclab.com/auth/realms/412/protocol/openid-connect/token
          GF_AUTH_GENERIC_OAUTH_API_URL: https://collaborauth.dvclab.com/auth/realms/412/protocol/openid-connect/userinfo
          GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH: contains(resource_access.grafana.roles[*], 'Admin') && 'Admin' || contains(resource_access.grafana.roles[*], 'Editor') && 'Editor' || 'Viewer'