version: "3"

services:
    keycloakmysql:
        image: mysql
        container_name: keycloakmysql
        hostname: keycloakmysql
        volumes:
            - /opt/keycloak/mysql/data:/var/lib/mysql
        privileged: true
        environment:
            - MYSQL_DATABASE=keycloak
            - MYSQL_USER=keycloak
            - MYSQL_PASSWORD=password
            - MYSQL_ROOT_PASSWORD=root_password
            
    keycloak:
        image: jboss/keycloak
        container_name: keycloak
        hostname: keycloak
        restart: always
        links: 
            - keycloakmysql
        ports:
            - 8080:8080
        volumes:
            - /opt/keycloak/realm-export.json:/tmp/realm-export.json
            - /opt/keycloak/keycloak-services-social-weixin-0.0.19.jar:/opt/jboss/keycloak/providers/keycloak-services-social-weixin-0.0.19.jar
            - /opt/keycloak/realm-identity-provider-weixin.html:/opt/jboss/keycloak/themes/base/admin/resources/partials/realm-identity-provider-weixin.html
            - /opt/keycloak/realm-identity-provider-weixin-ext.html:/opt/jboss/keycloak/themes/base/admin/resources/partials/realm-identity-provider-weixin-ext.html
        environment:
            - KEYCLOAK_USER=admin
            - KEYCLOAK_PASSWORD=hanwuji@412
            - DB_VENDOR=mysql
            - DB_ADDR=keycloakmysql
            - DB_PORT=3306
            - DB_DATABASE=keycloak
            - DB_USER=keycloak
            - DB_PASSWORD=password
            - PROXY_ADDRESS_FORWARDING=true
            - KEYCLOAK_IMPORT="/tmp/realm-export.json -Dkeycloak.profile.feature.upload_scripts=enabled"
        command:
            [   
                 "-b 0.0.0.0",
                 "-Dkeycloak.profile.feature.upload_scripts=enabled",
                 "-Dkeycloak.import=/tmp/realm-export.json",
                 "-Dkeycloak.profile.feature.docker=enabled",
                 "-Dkeycloak.profile.feature.token_exchange=enabled",
                 "-Dkeycloak.profile.feature.admin_fine_grained_authz=enabled"
            ]
        depends_on:
            - keycloakmysql
    
networks:
    default:
        external:
            name: keycloak-network
