version: '2'

services:
  db:
    container_name: nextcloud_mysql
    image: mysql
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - /opt/nextcloud/volumes/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=LvWo06Nv
      - MYSQL_PASSWORD=LvWo06Nv
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    container_name: nextcloud
    image: nextcloud:20.0.5
    restart: always
    ports:
      - 8011:80
    links:
      - db
    volumes:
      - /opt/nextcloud/volumes/nextcloud:/var/www/html
    environment:
      - SKELETON_DIRECTORY=""
      - MYSQL_PASSWORD=LvWo06Nv
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
